[theme]
base="dark"
primaryColor="#FF4B4B" # Un color de acento rojo para el botón y otros elementos
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
